config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :title, :author, :body, presence: true

  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :author, :body, presence: true

  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :author, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>XpLoIT News</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="bg-primary text-white text-center mb-2 p-2">

      <%= link_to root_path, class: 'text-white text-decoration-none' do %>
        <h1 class="display-7">Welcome to XNews</h1>
      <% end %>

      <p class="lead fs-6">
        <strong>Here you can find all that you need to learn about HydraVim and get up-to-date
          with all features and releases in first-hand
        </strong>
      </p>

    </div>

    <div class="container">
      <%= yield %>
    </div>

    <footer class="bg-primary text-white text-center mt-5 p-4">
      Copyright &copy XpLoITeam  <%= Date.current.year %>
    </footer>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>

  <div class="form-group mb-3">
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :author, style: "display: block" %>
    <%= form.text_field :author , class: 'form-control'%>
  </div>

  <div class="form-group mb-3">
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body , class: 'form-control', rows: 5 %>
  </div>

  <%= form.submit class: 'btn btn-success', data: { disable_with: 'Enviando..' } %>
<% end %>

app/views/posts/_post.html.erb
<div class="card bg-light mb-3">
  <div class="card-body">
    <h4><%= link_to post.title, post %></h4>

    <div class="text-muted mb-2">
      <em>Por <%= post.author %> (<%= l post.created_at, format: :short %>)</em>
    </div>

    <p> <%= post.body.truncate 200 %> </p>

    <p class="text-muted"> <%= pluralize post.comments.count, 'Comentario' %> </p>

    <%= link_to "Ver mais", post, class: 'btn btn-info' %>
    <%= link_to "Editar", edit_post_path(post) , class: 'btn btn-secondary' %>
    <%= link_to "Apagar", post, method: :delete, class: 'btn btn-danger' %>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Editar Postagem</h1>

<%= render "form", post: @post %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <%= render post %>
<% end %>

<hr>

<div class="text-end">
  <%= link_to "Criar novo post", new_post_path, class: "btn btn-info" %>
</div>

app/views/posts/new.html.erb
<h1>Nova Postagem</h1>

<%= render "form", post: @post %>

app/views/posts/show.html.erb
<div class="shadow bg-light p-5 rounded">

  <div class="text-center mb-5">
    <h1><%= @post.title %></h1>

    <p class="text-muted">
      <strong> Por <%= @post.author %> </strong><br>
      <%= l @post.created_at, format: :long %>
    </p>
  </div>

  <div class="px-5">
    <%= @post.body.gsub("\n", "<br>").html_safe %>
  </div>
</div>